// Generated by https://quicktype.io

export interface ProductDetailsResponse {
	id: string;
	model: Model;
	style: Style;
	inventory: Inventory;
	sizes: Size[];
	styleVariants: StyleVariant[];
	sizeChart: SizeChart;
}

export interface Inventory {
	inventoryAvailable: boolean;
	storeInventoryAvailable: boolean;
	warehouseInventoryAvailable: boolean;
	dropshipInventoryAvailable: boolean | null;
	inventoryAvailableLocations: string[] | null;
	preSell: boolean | null;
	backOrder: boolean | null;
	purchaseOrderDate: null | string;
}

export interface Model {
	id: ModelDocumentIDEnum;
	modelWebKey: string;
	companyNumber: string;
	banner: Banner;
	languageIsoCode: LanguageISOCode;
	active: boolean;
	number: number;
	name: Name;
	description: string;
	keywords: any[];
	brand: string;
	genders: string[];
	sports: string[];
	vendor: null;
	productHierarchy: ProductHierarchy;
	sizeChartId: string;
}

export type Banner = string;
// export enum Banner {
// 	Footlocker = "Footlocker",
// 	KidsFootlocker = "Kids Footlocker",
// }

export enum LanguageISOCode {
	EnUs = "en-us",
}

export type ModelDocumentIDEnum = string;
export type Name = string;
export type StyleDocumentIDEnum = string;

export interface ProductHierarchy {
	productTypes: string[];
	styles: string[];
	subStyles: string[];
}

export interface SizeChart {
	id: string;
	sizeChartGridMap: SizeChartGridMap[];
	sizeChartTipTx: string;
	sizeChartImage: string;
}

export interface SizeChartGridMap {
	label: string;
	sizes: string[];
}

export interface Size {
	id: string;
	productWebKey: string;
	styleDocumentId: StyleDocumentIDEnum;
	modelDocumentId: ModelDocumentIDEnum;
	companyNumber: string;
	banner: Banner;
	languageIsoCode: LanguageISOCode;
	active: boolean;
	productNumber: string;
	size: string;
	strippedSize: string;
	sizeVariants: null;
	upc: string;
	storeUpc: string;
	storeSku: StoreSku;
	price: Price;
	priceNet: null;
	inventory: Inventory;
}

export interface Price {
	listPrice: number;
	salePrice: number;
	formattedListPrice: FormattedPrice;
	formattedSalePrice: FormattedPrice;
	currencyIso: null;
	vendorShippingPrice: number | null;
	formattedVendorShippingPrice: FormattedPrice;
	priceRange: PriceRange;
	taxClassificationCode: null | string;
	topSalesAmount: number | null;
}

export type FormattedPrice = string;

export type PriceRange = string;

export type Sku = string;

export type StoreSku = string;

export interface Style {
	id: StyleDocumentIDEnum;
	sku: Sku;
	styleWebKey: string;
	modelWebKey: string;
	modelDocumentId: ModelDocumentIDEnum;
	companyNumber: string;
	banner: Banner;
	languageIsoCode: LanguageISOCode;
	active: boolean;
	description: string;
	color: Color;
	primaryColor: string;
	secondaryColors: string[];
	width: string;
	leagueName: string;
	playerName: string;
	teamName: string;
	fitVariant: string;
	keywords: string[];
	productDesignator: string;
	newArrivalDate: null | string;
	ageBuckets: any[];
	price: Price;
	priceNet: null;
	flagsAndRestrictions: { [key: string]: boolean | null };
	launchAttributes: LaunchAttributes;
	giftCardDenominations: number[] | null;
	eligiblePaymentTypes: { [key: string]: boolean | null };
	vendorAttributes: VendorAttributes;
	imageUrl: ImageURL | null;
}

export type Color = string;

export interface ImageURL {
	base: string;
	imageSku: string;
	variants: string[];
}

export interface LaunchAttributes {
	launchProduct: boolean;
	launchType: string;
	webOnlyLaunchMsg: string;
	webOnlyLaunch: boolean;
	launchDate: null | string;
	launchDisplayCounterEnabled: boolean;
	launchDisplayCounterKickStartTime: null | string;
}

export interface VendorAttributes {
	supplierSkus: string[];
}

export interface StyleVariant {
	active: boolean;
	styleWebKey: string;
	sku: Sku;
	upc: string;
	storeUpc: string;
	productWebKey: string;
	style: Name;
	color: Color;
	description: string;
	playerName: string;
	imageSku: string;
	size: string;
	ageBuckets: null;
	price: Price;
	priceNet: null;
	inventory: Inventory;
}
